@startuml Coworking System Use Case Diagram
left to right direction
actor "User" as user
rectangle "Coworking System" as CoworkingSystem {    
    usecase "Register" as register
    usecase "View\nOwn Appointment" as viewAppoint
    usecase "Manage\nAppointment" as manageAppt
    usecase "Manage\nHospital" as manageHospital
    usecase "View\nall Appointment" as manageCoworking
}

user -- register
user -- viewAppoint
user -- manageAppt

actor "Admin" as admin
register -- admin
manageCoworking -- admin
manageAppt -- admin
viewAppoint -- admin

@enduml
