@startuml
title "Authorization"
participant "User" as user
participant "Admin" as admin
participant "Server" as serverUML
participant "<<routes>>\nauth" as routesUML 
participant "<<middleware>>\nauth" as middlewareUML
participant "<<controllers>>\nauth" as ControlAuth
participant "<<models>>\nUser" as modelsUser
participant "MongoDB" as mongodbUML

   user ++
   admin ++
   serverUML ++
   routesUML ++
   middlewareUML ++
   modelsUser ++
   ControlAuth ++
   modelsUser ++
   mongodbUML ++
/'Register'/
opt
   user -> serverUML :req.post('/api/project/auth/register')
   admin -> serverUML
   serverUML -> routesUML :app.use('/api/project/auth', auth)
   routesUML -> ControlAuth :post("/register", register)
   ControlAuth -> modelsUser :User.create({ name, email, \ntelephone, password, role })
   modelsUser -> mongodbUML :create({ name, email, \ntelephone, password, role })
   mongodbUML --> modelsUser :user
   modelsUser --> ControlAuth :user
   ControlAuth -> modelsUser :user.getSignedJwtToken()
   modelsUser --> ControlAuth :token
   ControlAuth --> routesUML :response
   routesUML --> serverUML :response
   serverUML --> user :response
   serverUML --> admin 
end

/'Login'/
opt
   user -> serverUML :req.post('/api/project/auth/login')
   admin -> serverUML 
   serverUML -> routesUML :app.use('/api/project/auth', auth)
   routesUML -> ControlAuth :post('/login', login)
   ControlAuth -> modelsUser :User.findOne({ email }).\nselect('+password')
   modelsUser -> mongodbUML :findOne({ email }).\nselect('+password')
   mongodbUML --> modelsUser :user
   modelsUser --> ControlAuth :user
   ControlAuth -> modelsUser :user.matchPassword(password)
   modelsUser --> ControlAuth : match
   ControlAuth -> modelsUser :user.getSignedJwtToken()
   modelsUser --> ControlAuth :token
   ControlAuth --> routesUML :response
   routesUML --> serverUML :response
   serverUML --> user :response
   serverUML --> admin
end

/'getMe'/
opt
   user -> serverUML :req.get('/api/project/auth/me')
   admin -> serverUML
   serverUML -> routesUML :app.use('/api/project/auth', auth)
   routesUML->middlewareUML :protect(token)
   middlewareUML->middlewareUML :decoded
   middlewareUML->modelsUser :User.findById(decoded.id)
   modelsUser->mongodbUML :findById(decoded.id)
   mongodbUML --> modelsUser :user
   modelsUser --> middlewareUML :user
   middlewareUML -->routesUML :next()
   routesUML -> ControlAuth :get('/me', protect, getMe);
   ControlAuth -> modelsUser :User.findById(req.user.id)
   modelsUser -> mongodbUML :findById(req.user.id)
   mongodbUML --> modelsUser :user
   modelsUser --> ControlAuth :user
   ControlAuth --> routesUML :response
   routesUML --> serverUML :response
   serverUML --> user :response
   serverUML --> admin
end

/'log out'/
opt
   user -> serverUML :req.get('/api/project/auth/logout')
   admin -> serverUML
   serverUML -> routesUML :app.use('/api/project/auth', auth)
   routesUML -> ControlAuth :get('/logout', logout)
   ControlAuth -> ControlAuth :res.cookie("token", "none", \n{expires: new Date(Date.now() + 10 * 1000)\n,httpOnly: true,});
   /'ControlAuth -> ControlAuth :expire'/
   ControlAuth --> routesUML :response
   routesUML --> serverUML :response
   serverUML --> user :response
   serverUML --> admin
end
/'Additional'/
/'User Update Me'/
'/Update Me router.put("/updateMe",protect,updateMe);'/
opt
   user -> serverUML :req.put('/api/project/auth/updateMe')
   admin -> serverUML 
   serverUML -> routesUML :app.use('/api/project/auth', auth)
   routesUML -> middlewareUML:protect(token)
   middlewareUML->modelsUser :User.findById(decoded.id)
   mongodbUML --> modelsUser :user
   modelsUser --> middlewareUML :user
   middlewareUML -->routesUML :next()
   routesUML -> ControlAuth :put('/updateMe',updateMe);
   ControlAuth -> ControlAuth :!req.body.role
   ControlAuth -> modelsUser :User.findByIdAndUpdate\n(req.user.id,req.body,\n{new: true,runValidators: true})
   modelsUser -> mongodbUML :findByIdAndUpdate\n(req.user.id,req.body,\n{new: true,runValidators: true})
   mongodbUML --> modelsUser :User
   modelsUser --> ControlAuth :User
   ControlAuth --> routesUML :response
   routesUML --> serverUML :response
   serverUML --> user :response
   serverUML --> admin
end

/'Delete Me  router.delete("/deleteMe", protect, deleteMe, logout);'/
opt
   user -> serverUML :req.delete('/api/project/auth/deleteMe')
   admin -> serverUML 
   serverUML -> routesUML :app.use('/api/project/auth', auth)
   routesUML -> middlewareUML:protect(token)
   middlewareUML->modelsUser :User.findById(decoded.id)
   mongodbUML --> modelsUser :user
   modelsUser --> middlewareUML :user
   middlewareUML -->routesUML :next()
   routesUML -> ControlAuth :delete('/deleteMe', deleteMe)
   ControlAuth -> modelsUser :User.findById(req.user.id)
   modelsUser -> mongodbUML :findById(req.user.id)
   mongodbUML --> modelsUser :user
   modelsUser --> ControlAuth :user
   ControlAuth -> modelsUser :user.deleteOne()
   modelsUser -> mongodbUML :deleteOne()
   mongodbUML --> modelsUser :response
   modelsUser --> ControlAuth :response
   ControlAuth --> routesUML :response
   routesUML --> serverUML :response
   serverUML --> user :response
   serverUML --> admin 
end
/'User Delete Me'/
opt
   admin -> serverUML :req.get('/api/project/auth/getallusers')
   serverUML -> routesUML :app.use('/api/project/auth', auth)
   routesUML -> middlewareUML:protect(token)
   middlewareUML->modelsUser :User.findById(decoded.id)
   mongodbUML --> modelsUser :user
   modelsUser --> middlewareUML :user
   middlewareUML -->routesUML :next()
   routesUML -> middlewareUML :authorize('admin') 
   middlewareUML -> middlewareUML :roles.includes(req.user.role)
   middlewareUML --> routesUML :next()
   routesUML -> ControlAuth :get('/getallusers',getAllUsers)
   ControlAuth -> modelsUser :User.find(JSON.parse(queryStr)).populate('reservations')
   modelsUser -> mongodbUML :find(JSON.parse(queryStr)).populate('reservations')
   mongodbUML --> modelsUser :user
   modelsUser --> ControlAuth :coworkings
   ControlAuth -> ControlAuth :query.find({ role: 'user'})
   ControlAuth -> ControlAuth :req.query.select
   ControlAuth -> ControlAuth :req.query.sort
   ControlAuth --> routesUML :response
   routesUML --> serverUML :response
   serverUML --> user :response
   serverUML --> admin
end
/'Admin View All Users'/


@enduml